BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "token" (
	"TOKEN_ID"	INTEGER NOT NULL UNIQUE,
	"NAME"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("TOKEN_ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "token_value_usd" (
	"VALUE_ID"	INTEGER NOT NULL UNIQUE,
	"DATE"	TEXT NOT NULL,
	"VALUE_USD"	NUMERIC NOT NULL,
	"TOKEN_ID"	TEXT NOT NULL,
	PRIMARY KEY("VALUE_ID" AUTOINCREMENT),
	FOREIGN KEY("TOKEN_ID") REFERENCES "token"("TOKEN_ID")
);
CREATE TABLE IF NOT EXISTS "offer" (
	"OFFER_ID"	INTEGER NOT NULL UNIQUE,
	"TOKEN_ID"	INTEGER NOT NULL,
	"DATE"	TEXT NOT NULL,
	"USER_NAME"	TEXT NOT NULL,
	"FINISH_RATE"	REAL,
	"METHODS"	TEXT NOT NULL,
	"MAX_SINGLE_TRANS_AMOUNT"	REAL NOT NULL,
	"AVAILABLE"	REAL NOT NULL,
	"PRICE"	REAL NOT NULL,
	"USER_ID"	INTEGER NOT NULL,
	"ORDER_COUNT"	INTEGER NOT NULL,
	"MIN_SINGLE_TRANS_AMOUNT"	REAL NOT NULL,
	FOREIGN KEY("TOKEN_ID") REFERENCES "token"("TOKEN_ID"),
	PRIMARY KEY("OFFER_ID" AUTOINCREMENT)
);
INSERT INTO "token" ("TOKEN_ID","NAME") VALUES (1,'USDT'),
 (2,'BTC'),
 (3,'BUSD'),
 (4,'BNB'),
 (5,'ETH'),
 (6,'DAI');
COMMIT;
